use chrono::{DateTime, NaiveDate, Utc};
use serde::{Deserialize, Serialize};

#[derive(Debug, Serialize, Deserialize, sqlx::FromRow)]
pub struct GuardianSummary {
    pub id: uuid::Uuid,
    pub id_guardian_offer: String,
    pub date_guardian: Option<NaiveDate>,
    pub customer_id: String,
    pub account_name: Option<String>,
    pub equipment: Option<String>,
    pub inspection_frequency: Option<String>,
    pub basic_kit: Option<bool>,
    pub total: Option<f64>,
    pub discount: Option<f64>,
    pub total_end: Option<f64>,
    pub basic_kit_price: Option<f64>,
    pub acceptance_date: Option<NaiveDate>,
    pub audit_amount: Option<f64>,
    pub audit_comments: Option<String>,
    pub audit_date: Option<NaiveDate>,
    pub audit_number_invoice: Option<String>,
    pub audit_report: Option<String>,
    pub maintenance_checklist_number: Option<String>,
    pub maintenance_comments: Option<String>,
    pub maintenance_date: Option<NaiveDate>,
    pub maintenance_sat_amount: Option<f64>,
    pub maintenance_service_invoice: Option<String>,
    pub maintenance_spare_parts_offer: Option<String>,
    pub maintenance_status: Option<String>,
    pub maintenance_sat_date: Option<NaiveDate>,
    pub spare_parts_date: Option<NaiveDate>,
    pub spare_parts_material_amount: Option<f64>,
    pub spare_parts_material_invoice: Option<String>,
    pub summary_notes: Option<String>,
    pub summary_other1: Option<f64>,
    pub summary_other2: Option<f64>,
    pub summary_total_euros: Option<f64>,
    pub status: Option<String>,
    pub bill_date: Option<NaiveDate>,
    pub created_at: DateTime<Utc>,
}
