-- Fix column types: NUMERIC -> DOUBLE PRECISION for offers table
ALTER TABLE offers
    ALTER COLUMN diets TYPE DOUBLE PRECISION USING diets::DOUBLE PRECISION,
    ALTER COLUMN trip TYPE DOUBLE PRECISION USING trip::DOUBLE PRECISION,
    ALTER COLUMN trip_hours TYPE DOUBLE PRECISION USING trip_hours::DOUBLE PRECISION,
    ALTER COLUMN work_hours TYPE DOUBLE PRECISION USING work_hours::DOUBLE PRECISION,
    ALTER COLUMN total_hours TYPE DOUBLE PRECISION USING total_hours::DOUBLE PRECISION,
    ALTER COLUMN basic_kit_hours TYPE DOUBLE PRECISION USING basic_kit_hours::DOUBLE PRECISION,
    ALTER COLUMN basic_kit_price TYPE DOUBLE PRECISION USING basic_kit_price::DOUBLE PRECISION,
    ALTER COLUMN discount TYPE DOUBLE PRECISION USING discount::DOUBLE PRECISION,
    ALTER COLUMN hours_import TYPE DOUBLE PRECISION USING hours_import::DOUBLE PRECISION,
    ALTER COLUMN report_hours TYPE DOUBLE PRECISION USING report_hours::DOUBLE PRECISION,
    ALTER COLUMN total TYPE DOUBLE PRECISION USING total::DOUBLE PRECISION,
    ALTER COLUMN total_end TYPE DOUBLE PRECISION USING total_end::DOUBLE PRECISION;

-- Fix column types for prices table
ALTER TABLE prices
    ALTER COLUMN full_diet_rate TYPE DOUBLE PRECISION USING full_diet_rate::DOUBLE PRECISION,
    ALTER COLUMN half_diet_rate TYPE DOUBLE PRECISION USING half_diet_rate::DOUBLE PRECISION,
    ALTER COLUMN hotel_rate TYPE DOUBLE PRECISION USING hotel_rate::DOUBLE PRECISION,
    ALTER COLUMN hourly_rate_specialist TYPE DOUBLE PRECISION USING hourly_rate_specialist::DOUBLE PRECISION,
    ALTER COLUMN hourly_rate_technician TYPE DOUBLE PRECISION USING hourly_rate_technician::DOUBLE PRECISION,
    ALTER COLUMN km_rate TYPE DOUBLE PRECISION USING km_rate::DOUBLE PRECISION,
    ALTER COLUMN guardian_blades_discount TYPE DOUBLE PRECISION USING guardian_blades_discount::DOUBLE PRECISION,
    ALTER COLUMN guardian_spare_parts_discount TYPE DOUBLE PRECISION USING guardian_spare_parts_discount::DOUBLE PRECISION,
    ALTER COLUMN guardian_technician_discount TYPE DOUBLE PRECISION USING guardian_technician_discount::DOUBLE PRECISION;
