-- Fix clients_equipment NUMERIC -> DOUBLE PRECISION
ALTER TABLE clients_equipment
    ALTER COLUMN import_amount TYPE DOUBLE PRECISION USING import_amount::DOUBLE PRECISION,
    ALTER COLUMN workload TYPE DOUBLE PRECISION USING workload::DOUBLE PRECISION;

-- Fix guardian_summary NUMERIC -> DOUBLE PRECISION
ALTER TABLE guardian_summary
    ALTER COLUMN total TYPE DOUBLE PRECISION USING total::DOUBLE PRECISION,
    ALTER COLUMN discount TYPE DOUBLE PRECISION USING discount::DOUBLE PRECISION,
    ALTER COLUMN total_end TYPE DOUBLE PRECISION USING total_end::DOUBLE PRECISION,
    ALTER COLUMN basic_kit_price TYPE DOUBLE PRECISION USING basic_kit_price::DOUBLE PRECISION,
    ALTER COLUMN audit_amount TYPE DOUBLE PRECISION USING audit_amount::DOUBLE PRECISION,
    ALTER COLUMN maintenance_sat_amount TYPE DOUBLE PRECISION USING maintenance_sat_amount::DOUBLE PRECISION,
    ALTER COLUMN spare_parts_material_amount TYPE DOUBLE PRECISION USING spare_parts_material_amount::DOUBLE PRECISION,
    ALTER COLUMN summary_other1 TYPE DOUBLE PRECISION USING summary_other1::DOUBLE PRECISION,
    ALTER COLUMN summary_other2 TYPE DOUBLE PRECISION USING summary_other2::DOUBLE PRECISION,
    ALTER COLUMN summary_total_euros TYPE DOUBLE PRECISION USING summary_total_euros::DOUBLE PRECISION;
